### PR TITLE
Add JSON institute list file

### PR DESCRIPTION
**Pull request by Isoheptane**
I have noticed that the project is using CSV file to store data. However it is not easy to read and modify. JSON is more ideal for this kind of purpose, it has following advantages:
- Self describing, easy to read and modify
- Clear format, less possibility of format errors and parse errors
- Convenient for related developments

I have committed a JSON file with all institute mentioned in the CSV file.

I apologize for too much commits. I'm currently using a phone to do all of the works.

### CODE REVIEW

**Comment by BeiyanYunyi** [comment]
……有没有一种可能，Excel 就能编辑 csv？

**Comment by Isoheptane** [comment]
Excel is just too large for editing CSV files. Although the structure of CSV file is simple, it is still not friendly for modifying via text editors because columns may not align straight.

Besides, I have noticed that one institute may have multiple names/locations/info sources. Separate using `""` doesn't seem to be fair.

**Comment by BeiyanYunyi** [comment]
> it is still not friendly for modifying via text editors

显然问题的核心在于**贡献者们**的组成：程序员 or 其它人？习惯用文本编辑器还是 Excel？

**Comment by FunctionSir** [comment]
Thanks!

**Pull request merged**
